### PR TITLE
Fixed MCU V-Pot weirdness

### PR DESCRIPTION
**Pull request by ottworks**
Knobs aren't buttons.

### CODE REVIEW

**Comment by teotigraphix** [comment]
> Knobs aren't buttons.

On the studio they are. I would have to check this code on my controller to see if it's breaking anything. Sorry man, I am right in the middle of some Android app releases so my time is 0. :)

**Comment by 0tt** [comment]
I left the knob touch buttons in, so those should be fine.

**Comment by 0tt** [comment]
Would you rather I try to break my changes up into several pulls that may have merge conflicts, or just commit to master on my own fork and have one massive pull request when I'm satisfied?

**Comment by teotigraphix** [comment]
Well, what is your end goal? Are you aiming to change any major implementations?

It's obvious you understand what I wrote, so maybe on massive pull if you are not totally changing the framework I wrote.

I was planning on coming back to this eventually but since you are into it, I just am curious what you want to be satisfied with.

**Comment by teotigraphix** [comment]
Ok, well the easiest thing would be for me to add you to the repository. :)

Dealing with pulls when you are actually developing it sucks ass. haha

Just don't go crazy but I did say I wasn't satisfied with the UX when I was working on it, so if you have ideas, right on. 

Dom from Bitwig helped me on some of the ideas but others I had to ride by the seat of my pants because the Maschine controllers are not like the Push when it comes to integrating them into the DAW.

**Comment by 0tt** [comment]
That would be nice. I'll try to make any changes to the framework upstream.

**Comment by teotigraphix** [comment]
Ok, just make sure you don't break anything, seriously. :) Push4Bitwig gets used by a lot and Moss would be really pissed off if we broke anything, changes have to be totally justified.

If in doubt with any framework classes ask first because you could just override the prototype before doing anything in Framework4Bitwig code.

**Comment by 0tt** [comment]
Yeah, don't add me to Framework4Bitwig. I'll open issues/pulls if I need
anything.

**Comment by teotigraphix** [comment]
I can't find you when I try to add a collaborator. There are like 3 Ott that come up, non with your graphic avatar.

**Comment by 0tt** [comment]
It's with a numeric 0.

**Comment by 0tt** [comment]
By the way @teotigraphix, how do I switch mode banks without doing the dropdown?

**Pull request merged**
